version: '3.0'

services:
  front:
    container_name: 'front'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    restart: 'always'